version: '3.1'

services:
  www-wglobal:
    container_name: www-wglobal
    image: www-wglobal
    build: .
    ports:
      - "3100:3000"
    networks:
      - homedock

networks:
  homedock:
    external: true
